#!/usr/bin/env python3
"""
ASCEND fact collector.

Walks every host in the lab, runs each probe, applies the derivation rules in
scope.yaml, and writes environment_graph/facts.json — the file the path
enumerator, the FastAPI service and the dashboard all read.

    python3 collectors/collect.py                    # collect from the Docker lab
    python3 collectors/collect.py --save-raw raw.json
    python3 collectors/collect.py --from-raw raw.json   # re-derive, no lab needed

The --from-raw path matters beyond convenience: it separates *collection* from
*judgement*. A captured raw file can be replayed through changed rules to see
exactly which findings the change adds or removes, and the derivation layer can
be tested with no containers running at all.

Exit codes: 0 collected, 1 collection error, 2 nothing found.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "collectors"))

import derive                                          # noqa: E402
from transport import DockerTransport, LocalTransport  # noqa: E402
from probes import (accounts, cred_files, docker_socket,  # noqa: E402
                    kernel, ports, reachability, ssh_keys, sudo, suid)

COLLECTOR_VERSION = "1.0.0"

SCOPE_PATH = ROOT / "scope.yaml"
KG_PATH    = ROOT / "knowledge_graph" / "pack.json"
FACTS_PATH = ROOT / "environment_graph" / "facts.json"
REPORT_PATH = ROOT / "environment_graph" / "collection_report.json"


def load_scope() -> dict:
    try:
        import yaml
    except ImportError:
        sys.exit("PyYAML is required to read scope.yaml:  pip install pyyaml")
    with open(SCOPE_PATH) as fh:
        return yaml.safe_load(fh)


def load_kg() -> dict:
    if not KG_PATH.exists():
        return {}
    with open(KG_PATH) as fh:
        return json.load(fh)


# ─────────────────────────────────────────────────────────────────────────────
# Collection
# ─────────────────────────────────────────────────────────────────────────────

def collect_host(host: str, tp, scope: dict, verbose: bool) -> dict:
    """Run every local probe against one host. Order matters: the account list
    is needed by the sudo and authorized_keys probes, so it is collected first
    and threaded through as scope['_accounts']."""
    def say(msg):
        if verbose:
            print(f"    {msg}", flush=True)

    say("accounts")
    host_accounts = accounts.collect(host, tp, scope)
    scoped = {**scope, "_accounts": host_accounts}

    say("kernel");        kern = kernel.collect(host, tp, scoped)
    say("sudo");          sudo_data = sudo.collect(host, tp, scoped)
    say("suid");          suid_data = suid.collect(host, tp, scoped)
    say("cred files");    creds = cred_files.collect(host, tp, scoped)
    say("authorized_keys"); authkeys = ssh_keys.collect(host, tp, scoped)
    say("listening ports"); listening = ports.collect(host, tp, scoped)
    say("docker socket"); sock = docker_socket.collect(host, tp, scoped)

    return {
        "accounts":        host_accounts,
        "kernel":          kern,
        "sudo":            sudo_data,
        "suid":            suid_data,
        "cred_files":      creds,
        "authorized_keys": authkeys,
        "ports":           listening,
        "docker_socket":   sock,
    }


def collect_all(hosts: list[str], tp, scope: dict, verbose: bool) -> dict:
    raw = {}
    for host in hosts:
        print(f"  collecting {host} via {tp.name}...", flush=True)
        raw[host] = collect_host(host, tp, scope, verbose)

    print(f"  probing reachability across {len(hosts)} hosts "
          f"(real TCP connections)...", flush=True)
    listening = {h: raw[h]["ports"] for h in hosts}
    matrix = reachability.collect_matrix(hosts, tp, listening)

    return {"hosts": raw, "reachability_matrix": matrix}


# ─────────────────────────────────────────────────────────────────────────────
# Assembly
# ─────────────────────────────────────────────────────────────────────────────

def build_facts(capture: dict, scope: dict, kg: dict, source: str) -> tuple[dict, dict]:
    raw = capture["hosts"]
    matrix = capture["reachability_matrix"]

    hosts = derive.derive_hosts(raw, scope)
    host_accounts = derive.derive_accounts(raw)
    credentials, by_fingerprint = derive.derive_credentials(raw, scope)
    reach = derive.derive_reachability(matrix)
    vectors, skipped = derive.derive_vectors(raw, scope, kg, by_fingerprint)

    inventory = scope.get("inventory", {})
    now = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()

    facts = {
        "_comment": (
            "GENERATED by collectors/collect.py — do not edit by hand. Every host, "
            "account, credential, reachability edge and vector below was derived "
            "from a live probe of the lab under a rule in scope.yaml. Each item "
            "carries features.provenance: 'observed' means a probe measured it, "
            "'declared' means an operator supplied it (roles, asset values, and — "
            "in a container lab — per-host kernel versions). Re-generate with: "
            "python3 collectors/collect.py"
        ),
        "_meta": {
            "collected_at":      now,
            "collector_version": COLLECTOR_VERSION,
            "source":            source,
            "schema":            "docs/02 section 4",
            "hosts_probed":      len(raw),
            "provenance_legend": {
                "observed": "measured on the live host by a probe",
                "declared": "supplied by the operator; no scan could produce it",
            },
            "verification_status": (
                "NOT EXECUTION-VERIFIED. Every vector has verified_exploitable: null "
                "because no verifier has run. config_exploitable: true means the "
                "configuration required by the technique is present, which is a "
                "weaker claim than 'this exploit works here'."
            ),
        },
        "entry":       inventory.get("entry", {}),
        "crown_jewel": inventory.get("crown_jewel", {}),
        "hosts":        hosts,
        "accounts":     host_accounts,
        "credentials":  credentials,
        "reachability": reach,
        "vectors":      vectors,
    }

    report = {
        "collected_at": now,
        "source": source,
        "hosts_probed": sorted(raw),
        "counts": {
            "hosts": len(hosts), "accounts": len(host_accounts),
            "credentials": len(credentials), "reachability_edges": len(reach),
            "vectors": len(vectors), "conditions_examined_and_skipped": len(skipped),
        },
        # Conditions that were looked at and deliberately NOT reported. This is
        # the evidence that the rules discriminate rather than flag everything.
        "skipped": skipped,
        "reachability_attempts": matrix,
    }
    return facts, report


# ─────────────────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(description="Collect ASCEND environment facts.")
    ap.add_argument("--transport", choices=["docker", "local"], default="docker")
    ap.add_argument("--prefix", default="ascend-",
                    help="container name prefix (docker transport)")
    ap.add_argument("--hosts", nargs="*",
                    help="explicit host list; default is auto-discovery")
    ap.add_argument("--out", default=str(FACTS_PATH))
    ap.add_argument("--report", default=str(REPORT_PATH))
    ap.add_argument("--save-raw", metavar="PATH",
                    help="write the raw probe capture before derivation")
    ap.add_argument("--from-raw", metavar="PATH",
                    help="re-derive from a saved capture; runs no probes")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()

    scope = load_scope()
    kg = load_kg()

    if args.from_raw:
        with open(args.from_raw) as fh:
            capture = json.load(fh)
        source = f"replay:{Path(args.from_raw).name}"
        print(f"re-deriving from {args.from_raw} (no probes run)")
    else:
        try:
            tp = DockerTransport(prefix=args.prefix) if args.transport == "docker" \
                else LocalTransport()
        except RuntimeError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1

        hosts = args.hosts or tp.available_hosts()
        if not hosts:
            print(f"error: no lab hosts found. Is the lab up?\n"
                  f"       bash lab/up.sh", file=sys.stderr)
            return 2

        print(f"ASCEND collector {COLLECTOR_VERSION} — {len(hosts)} host(s): "
              f"{', '.join(hosts)}")
        capture = collect_all(hosts, tp, scope, args.verbose)
        source = f"{tp.name}:{args.prefix}" if args.transport == "docker" else "local"

        if args.save_raw:
            Path(args.save_raw).parent.mkdir(parents=True, exist_ok=True)
            with open(args.save_raw, "w") as fh:
                json.dump(capture, fh, indent=2, sort_keys=True)
            print(f"  raw capture -> {args.save_raw}")

    facts, report = build_facts(capture, scope, kg, source)

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w") as fh:
        json.dump(facts, fh, indent=2)
        fh.write("\n")
    with open(args.report, "w") as fh:
        json.dump(report, fh, indent=2)
        fh.write("\n")

    _summarise(facts, report, args.out, args.report)
    return 0


def _summarise(facts: dict, report: dict, out: str, report_path: str) -> None:
    def rel(path: str) -> str:
        """Repo-relative when the output is inside the repo, absolute otherwise
        (--out may legitimately point anywhere)."""
        resolved = Path(path).resolve()
        try:
            return str(resolved.relative_to(ROOT))
        except ValueError:
            return str(resolved)

    counts = report["counts"]
    print(f"\ncollected: {counts['hosts']} hosts, {counts['accounts']} accounts, "
          f"{counts['credentials']} credentials, {counts['reachability_edges']} "
          f"reachability edges, {counts['vectors']} vectors")

    if facts["reachability"]:
        print("\nreachability (measured, not declared):")
        for edge in facts["reachability"]:
            print(f"    {edge['from']:>8} -> {edge['to']:<8} "
                  f"{edge['service']}/{edge['port']}")

    for cred in facts["credentials"]:
        hosts_granted = sorted({g["host"] for g in cred["grants"]})
        if len(hosts_granted) > 1:
            print(f"\n  ** CREDENTIAL REUSE: {cred['cred_id']} "
                  f"({cred['features']['fingerprint'][:26]}...) is accepted on "
                  f"{len(hosts_granted)} hosts: {', '.join(hosts_granted)}")

    print("\nvectors:")
    for vec in facts["vectors"]:
        prov = vec["features"]["provenance"]
        mark = "  " if prov == "observed" else " !"
        print(f"  {mark}{vec['vector_id']:<34} {vec['technique']:<12} "
              f"{vec['host']:<6} [{prov}]")
    if any(v["features"]["provenance"] == "declared" for v in facts["vectors"]):
        print("     ! = derived from a declared fact, not a measured one")

    if report["skipped"]:
        print(f"\nexamined and NOT reported ({len(report['skipped'])}):")
        for entry in report["skipped"][:8]:
            subject = entry.get("path") or entry.get("rule") or entry.get("cve", "")
            print(f"    {entry['host']:<6} {entry['technique']:<10} "
                  f"{str(subject)[:42]:<42} {entry['reason']}")
        if len(report["skipped"]) > 8:
            print(f"    ... {len(report['skipped']) - 8} more in {rel(report_path)}")

    print(f"\nwrote {rel(out)} and {rel(report_path)}")
    print("next:  python3 enumerator/pathfinder.py")


if __name__ == "__main__":
    sys.exit(main())
